# Generated by Django 3.1.3 on 2021-05-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabo', '0003_comment_p_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_p',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posting',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
