# Generated by Django 3.1.3 on 2021-05-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabo', '0006_auto_20210524_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='tag',
            field=models.CharField(choices=[('C', 'Java'), ('Jave', 'D')], max_length=4),
        ),
    ]
