# Generated by Django 3.1.3 on 2021-05-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabo', '0008_auto_20210524_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='tag',
            field=models.CharField(max_length=10),
        ),
    ]
