# Generated by Django 3.1.3 on 2021-05-24 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tabo', '0009_auto_20210524_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_p',
            name='voter',
            field=models.ManyToManyField(related_name='voter_comment_p', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posting',
            name='voter',
            field=models.ManyToManyField(related_name='voter_posting', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='co_comment_p',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_co_comment_p', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment_p',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_comment_p', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='posting',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_posting', to=settings.AUTH_USER_MODEL),
        ),
    ]
