# Generated by Django 3.1.3 on 2021-06-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabo', '0011_co_comment_p_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
