# Generated by Django 3.1.3 on 2021-06-12 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabo', '0013_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('posting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tabo.posting')),
            ],
        ),
    ]
